[package]
name = "dazitui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
crossterm = "0.29.0"
dazitui-core = { version = "1.0.5", path = "../dazitui-core", features = ["online"] }
image = "0.25.10"
notify = "8.2.0"
ratatui = "0.30.2"
ratatui-image = { version = "11.0.6", default-features = false, features = ["crossterm", "image-defaults"] }
ratatui-themes = "0.3.0"
unicode-width = "0.2.0"
